### ISSUE TITLE
How can i receive signal in the jvm?

### ISSUE THREAD

**Issue by VFT** [Yelp/dumb-init#133]
I use /bin/bash to run jvm as a child process, but i can't receive signal in the jvm.

`Dockerfile`:
```bash
ENTRYPOINT ["/dumb-init", "--", "/docker-entrypoint.sh"]
```

and `docker-entrypoint.sh`:
```bash
#!/usr/bin/dumb-init /bin/bash

source `dirname $0`/init-product.sh

if [ -z "$POOL_TYPE" ]; then
  source `dirname $0`/init.sh $RESOURCE_ID
  echo "****FINISHED****"
else
  echo "****FINISHED****"
  java -Xmx64m -Xms16m -Xmn8m -Xss1m -XX:ReservedCodeCacheSize=5m -XX:NewRatio=3 -jar /usr/local/agent/agent-1.0.1.jar $POOL_TYPE
fi
```

**Comment by asottile** [comment]
This _should_ work as written, a few oddities I notice:

1. Your entrypoint mentions /dumb-init and your shebang mentions /usr/bin/dumb-init

I believe your process tree will look something like this:

```
/dumb-init
+--- /usr/bin/dumb-init
      +--- /bin/bash
            +--- java ...
```

Since you're using `/dumb-init` in your entrypoint you can probably eliminate it in your shebang?

2. You've got an unnecessary /bin/bash in your final process tree

If you do this:

```diff
-    java -Xmx64m ...
+    exec java -Xmx64m ...
```

and the above your process tree should look like:

```
/dumb-init
+--- java ...
```

That said, I don't think either of these issues should prevent signaling of the jvm.  Is there a specific signal that isn't getting through?  Does the `--rewrite ...` argument to `dumb-init` help with giving the jvm a signal it does handle?

**Comment by TNTest** [comment]
@asottile It is worked followd by your suggestion (#issuecomment-274352422) . Thx.

**Comment by VFT** [comment]
@asottile Thanks for your guide,it is worked.

**Comment by asottile** [comment]
No problem!  Thanks for the question :)

**Comment by sheldonhull** [comment]
@asottile // @VFT 
Quick followup question, when you mention unnecessary  `/bin/bash` in the shebang do you mean it should be completely omitted? What should it look like when done correctly based on your directions

Is this correct for the process tree or since entry-point defines dumb-init does this inherit correctly?

```
#!/bin/bash

source `dirname $0`/init-product.sh

if [ -z "$POOL_TYPE" ]; then
  source `dirname $0`/init.sh $RESOURCE_ID
  echo "****FINISHED****"
else
  echo "****FINISHED****"
exec java -Xmx64m -Xms16m -Xmn8m -Xss1m -XX:ReservedCodeCacheSize=5m -XX:NewRatio=3 -jar /usr/local/agent/agent-1.0.1.jar $POOL_TYPE
fi
```

**Comment by asottile** [comment]
yep that looks correct as long as you have the `ENTRYPOINT` set as OP does
