### ISSUE TITLE
Can you add the ARM binary?

### ISSUE THREAD

**Issue by ulm0** [Yelp/dumb-init#138]
Hi, everyone.
Been using the dumb-init on some arm devices for a couple of [GitLab Runners i built for ARM](https://gitlab.com/klud/gitlab-runner), but i'm facing a "problem", thing is i have to compile it within the build process each time i update the GitLab image to a new runner version and been wondering if you can add the arm binary to your v1.2.0 [files release](https://github.com/Yelp/dumb-init/releases/tag/v1.2.0), so i just have to `curl` / `wget` it when building the image instead of compiling it which ends being a heavy image.

In case you dont have an arm device, I compiled dumb-init on a RPi3 i have, the binary is here: [dumb-init_1.2.0_armhf](https://github.com/Yelp/dumb-init/files/923795/dumb-init-compile.zip)

**Comment by chriskuehl** [comment]
Thanks for the question! I'd be okay with including a binary (easy to add stuff to the release) but would prefer if we could incorporate that into the build process somehow so that we can do it easily for any new releases as well.

Do you have any suggestions for how we might do that? I think ideally it'd be a makefile target that could run on amd64 (since that's what we all run / what the CI runs) but cross-compile to armhf. I'm not sure how practical that is?

**Comment by chriskuehl** [comment]
Another option for anyone using arm could be to grab the "official" Debian package: https://packages.debian.org/stretch/dumb-init

You can extract them to just grab the binary if you'd like. They have builds for a bunch of different architectures which might work for you (not statically-linked like the ones we provide, though, which may or may not matter for your use-case).

**Comment by klud1** [comment]
> Do you have any suggestions for how we might do that? I think ideally it'd be a makefile target that could run on amd64 (since that's what we all run / what the CI runs) but cross-compile to armhf. I'm not sure how practical that is?

I'm kinda new to Docker stuff, but i've found this article [Setup a simple CI pipeline to build Docker images for ARM](https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/) a few weeks ago, they use QEMU and Travis CI for the builds, I could learn more about it if it's needed. That being said, the times I build for ARM I use the pipelines i have in GitLab using their CI and the ARM runners i built, those could be used, though i don't think you're willing to import your project and move to GitLab.

> Another option for anyone using arm could be to grab the "official" Debian package: https://packages.debian.org/stretch/dumb-init
You can extract them to just grab the binary if you'd like. They have builds for a bunch of different architectures which might work for you (not statically-linked like the ones we provide, though, which may or may not matter for your use-case).

I know i could do that, problem is i always try to build images based on alpine,  just installing necessary stuff in order to get an image as lightweight as possible.

That's why i just updated my [.gitlab-ci.yml](https://gitlab.com/klud/gitlab-runner/blob/master/.gitlab-ci.yml) file for the runners, separating the build process in two jobs, one for building the dumb-init binary and pass it to the next one to build the actual runner image.

**Comment by asottile** [comment]
Here's one way (using the debian packages) (without debian infrastructure):

```
wget http://ftp.us.debian.org/debian/pool/main/d/dumb-init/dumb-init_1.2.0-1_armhf.deb
ar -x *.deb
tar -xvf data.tar.xz
ls usr/bin/dumb-init
```

Output:
```
...
$ ls usr/bin/dumb-init 
usr/bin/dumb-init
```

**Comment by klud1** [comment]
@asottile tysm, gonna give it a try.

**Comment by hrw** [comment]
arm64 and ppc64le please then too.

Kolla is using dumb-init for openstack container images and I have to build dumb-init for those architectures.

**Comment by everflux** [comment]
I would like to leverage dumb-init for multi-arch docker images as well. Would be really helpful if you could provide releases for arm and arm64. This would result in just using an arch-dependant download while avoiding a totally different process for other architectures (download of debian package and ripping it apart)

**Comment by chriskuehl** [comment]
@everflux any ideas for how we can build an ARM binary? I'm definitely open to the idea—we just recently starting including `ppc64le` too—but we need some way to actually build it (for `ppc64le`, we're using Travis's support for it).

**Comment by everflux** [comment]
You could build it inside a docker build image using QEMU to emulate the target patform.
afaik travis supports using docker images as build container.

You could try to use this step during the build
```
docker run --rm --privileged multiarch/qemu-user-static:register --reset
```
then using a docker environment like
```
FROM multiarch/alpine:aarch64-v3.7
````
should work for ARM 64. (You need to install compiler etc)

Though QEMU is rather slow, it will work on x86 platforms to build arm binaries.

**Comment by ekristen** [comment]
+1 please support ARM64 bit.

**Comment by sr229** [comment]
Please be noted Alpine has a x86 packaged version in Alpine. I'll contact the maintainer to provide aarch64 and armv7l packages

**Comment by sr229** [comment]
@ekristen aarch64 is already supported, some distros like [Alpine](https://pkgs.alpinelinux.org/package/edge/community/aarch64/dumb-init) has them prebuilt for you.

@ulm0 I believe this is what you're looking for as well

**Comment by hrw** [comment]
Travis CI provides arm64 builders...

**Comment by asottile** [comment]
@hrw would you like to submit a PR? should be pretty easy to extend what we already have: https://github.com/Yelp/dumb-init/blob/4d3debba4d355f8ae93010f558f4cd3fdf00b2b9/.travis.yml#L5-L15

**Comment by hrw** [comment]
@asottile https://github.com/Yelp/dumb-init/pull/197 submitted. Hope that properly.

**Comment by samrocketman** [comment]
gcc has arm options

* https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html
* https://raspberrypi.stackexchange.com/questions/2046/which-cpu-flags-are-suitable-for-gcc-on-raspberry-pi

**Comment by chriskuehl** [comment]
Thanks @hrw @asottile! PR merged and there are now arm64 builds uploaded at:
* https://yelp-travis-artifacts.s3.amazonaws.com/dumb-init/197/itest_buster-linux/dist/dumb-init_1.2.2_arm64 (binary)
* https://yelp-travis-artifacts.s3.amazonaws.com/dumb-init/197/itest_buster-linux/dist/dumb-init_1.2.2_arm64.deb (Debian package)

I've also uploaded these under the GitHub releases tab for 1.2.2.

**Comment by hrw** [comment]
115 megabytes saved in an image due to one binary ;D

**Comment by watercolor** [comment]
I suggest dumb-init better rewrite in Go, then you can compile dumb-init to multi architectures, just specify GOARCH flag when go build.  like GOARCH=arm64, etc.
multi arch compile is supported in MacBook.

**Comment by asottile** [comment]
lol
