### ISSUE TITLE
Recommended way to do template processing

### ISSUE THREAD

**Issue by nikolay** [Yelp/dumb-init#139]
Base on environment variables, we need to change certain configuration files. As [dockerize](https://github.com/jwilder/dockerize) is too huge, I am using dumb-init and it works better and it's even tinier than [tini](https://github.com/krallin/tini) (pun intended). What is the best practice to do the one-time template processing right before actually launching the main process such as [nginx](http://nginx.org/)?

I think this is a very common use case and documenting this in the [README.md](https://github.com/Yelp/dumb-init/blob/master/README.md) would be of big service to all who are starting to use your tool!

**Comment by asottile** [comment]
Here's the pattern I usually use, we should update the README:

```dockerfile
CMD ["bash", "-c", "./setup && exec dumb-init exe"]
```

**Comment by chriskuehl** [comment]
It's probably slightly better to use dumb-init first so that it's always pid1?

```Dockerfile
CMD ["dumb-init", "bash", "-c", "./setup && exec exe"]
```

**Comment by asottile** [comment]
truuuuuue, yeah all the more reason to add it to the readme lol

**Comment by nikolay** [comment]
@chriskuehl @asottile Excuse my ignorance, but won't this unnecessarily keep the shell process though? I already have it like this, but I wanted to have a "no repercussions" way.

**Comment by chriskuehl** [comment]
@nikolay "exec" replaces the bash process with the process you're execing.

If you didn't exec at the end (and just called `exe`), it's true that bash would stay around forever. If you exec, then the shell only exists for a brief instant at the start (while doing your setup/templating) and then gets replaced.

**Comment by nikolay** [comment]
@chriskuehl See, I am ignorant! 😄 Thank you very much! This is a great way to de-dockerize images!

**Comment by nikolay** [comment]
It possibly would be a nice microfeature to have an optional `boot` folder passed to dumb-init so that it can `run-parts` with it before doing anything...

**Comment by rangerelf** [comment]
That would penalize people who don't need a run-parts functionality in dumb-init, by bloating it unnecessarily.

My preference is setting dumb-init as entrypoint and anything in cmd is a child of dumb-init.

**Comment by chriskuehl** [comment]
Yeah, I think dumb-init probably isn't the right layer to implement this functionality at. There's just too many slightly different use-cases around pre-start scripts and it'd be hard to get them all right. I like the idea of keeping dumb-init to basically the bare minimum needed for a "correct" init system, which is basically handling signals and 

We definitely can and should talk about some ways to implement this though in the README, since lots of people want to do something like this at container start (but before starting their main process). I'll start a branch to add a section to the docs.

**Comment by nikolay** [comment]
@chriskuehl I'm more against bloat than you can ever imagine! Sorry, for not being clear - all I had in mind is to be able to specify an optional init (pre-start?) script, which is a common pattern, so that we can use `ENTRYPOINT` in its JSON format and not have to bloat the following `CMD` and deal with escaping and stuff. I'm having in mind base images, because, for example, I can release an image that has templating baked in, and people can add their custom `CMD` without having to remember to still call my pre-start script, etc.

**Comment by chriskuehl** [comment]
(oops, didn't mean to close this issue with discussion still going on)

I think there's definitely some valid use-cases here, but I'm thinking it's probably better to err on the side of keeping dumb-init as minimal as possible. The original idea of dumb-init was to have a binary we could just put in front of any command to get rid of special Docker behavior. The bash solution admittedly isn't very pretty, but at least it works well, so I'm tempted to just leave this issue after documenting how we suggest to achieve a pre-start script. Does that sound reasonable to you?

**Comment by nikolay** [comment]
Okay, fair enough!

**Comment by chriskuehl** [comment]
thanks for filing the issue!

**Comment by nikolay** [comment]
@chriskuehl You're welcome and thanks for your great work!

**Comment by rangerelf** [comment]
Well, it's just a couple of shell lines to do a kind of run-parts initialization, or to have your main startup script do a run-parts kind of initialization:
```
#!/bin/sh
# Run all the scripts in the $1 directory.
for s in "$1"/*.sh ; do
  test -x "$s" && . "$s"
done
exit 0
```

In this example it checks the `x` permission bit but you could omit that and just run them indiscriminately; thinking further, there's no reason for "optional" scripts to be present in the container, only stuff that's actually going to be run.  The only warning is that since the scripts are sourced in, don't do an `exit` in them or you'll kill the container, but that's a one-time mistake.

So the `Dockerfile` becomes something like:

```
COPY my-init-scripts /app/init.d
COPY startup.sh /app/startup.sh
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/app/startup.sh", "/app/init.d"]
```

**Comment by nikolay** [comment]
@rangerelf Okay, nice, but `run-parts` is pre-installed.

**Comment by samrocketman** [comment]
I've used runit for service startup in a container.  Similar to phusion baseimage but using dumb-init.
