### ISSUE TITLE
Does it have restarting capabilities?

### ISSUE THREAD

**Issue by i0natan** [Yelp/dumb-init#156]
Can it restart the child-process when it crashes?

**Comment by samrocketman** [comment]
Not as far as I know.  It's not a watchdog process which keeps other processes alive.  Its functionality is simple in that it handles all of the functions of `/sbin/init` without actually starting any services (e.g. process reaping).

**Comment by chriskuehl** [comment]
Yeah, as @samrocketman says, it can't restart processes. In my humble opinion, I think this is a job that is better left to real process supervisors (I'm partial to `runit`; another option is `supervisord`). In theory it would be fairly simple to just restart the process, but it can get somewhat complicated (for example, should it sleep between restart attempts? should it eventually give up? what happens if you get a signal while the process is down? etc.).

**Comment by chriskuehl** [comment]
@i0natan going to close this as answered, feel free to reopen if you still have questions!
