### ISSUE TITLE
Cut release to depricate python2?

### ISSUE THREAD

**Issue by mtkunkel** [Yelp/dumb-init#194]
It appears dumb-init is on the Fedora deprecation list due to python2 dependencies despite  migration work already done in https://github.com/Yelp/dumb-init/pull/187.

Is it time to cut a release so python2 is fully removed?

Link to fedora announcement: https://lists.fedoraproject.org/archives/list/desktop@lists.fedoraproject.org/message/VZEZ57YB347YALV4HVGSN67SXEY2R66N/

**Comment by asottile** [comment]
I'm not sure why fedora packaged it that way, python2 has always been optional for dumb-init and test-only (it's a C binary after all!).  Feels like their packager made a mistake?

Please reach out to the packager for fedora to have them fix this 👍

**Comment by chriskuehl** [comment]
++ to what asottile said

If they currently have a dependency on python 2 due to the tests, note that the tests have always supported python 3 as well, so they could just change the interpreter they're running the tests with without needing to change any of the code or test files.

Also note that we recently changed the tests to only support python 3 (#187); they could pull in those changes if desired. (I don't really want to cut a new release just for this change though, as the dumb-init code did not change and the tests aren't part of the release.)
