### ISSUE TITLE
Duplicate Work with Tini Init

### ISSUE THREAD

**Issue by andrewhowdencom** [Yelp/dumb-init#63]
Hi All, 

I love this solution. However, there is parallel work that appears at first glance to be similar at https://github.com/krallin/tini. Is there some notable difference between the two that I can't discern? 

Cheers,

**Comment by chriskuehl** [comment]
@andrewhowdencom thanks for the question!

tini is quite similar to dumb-init, especially for use in Docker containers. The defaults are a little different (dumb-init by default creates a session rooted at the child and proxies signals to the process group started there, and I think tini by default proxies signals only to the immediate child), but I believe tini supports a similar mode as well (and dumb-init also supports the single-child mode).

I think for use in Docker you will find them pretty much equivalent.

At Yelp we use dumb-init extensively in our Docker containers (in basically all of the hundreds of images we have), but we've also started using it some surprising cases. For example, in [our system for running development environments](https://github.com/Yelp/pgctl) (which involves launching lots of services at once, similar to docker-compose but without requiring each service to be in Docker), we have a lot of "services" that involve launching 3-4 processes, and it's difficult to make sure they all get killed. Using dumb-init puts dumb-init at the "root" of the service, with the 3-4 processes below it, and means you can just signal dumb-init in order to kill all the various processes.

[Here's](https://github.com/Yelp/yelp_clog/pull/16) a concrete example of a really unexpected use-case. I don't really know how tini compares for use outside of Docker, or whether that's even a concern for you.

I can say that we do use dumb-init very extensively and I can't imagine us not continuing to support it in the foreseeable future.

(disclaimer: I haven't significantly tested or reviewed tini myself, but it certainly seems solid from looking at the code)

**Comment by chriskuehl** [comment]
(closing this for now, but feel free to reopen or ask other questions!)

**Comment by andrewhowdencom** [comment]
Thanks for this amazing response!
