### ISSUE TITLE
wget installation does not work on Alpine

### ISSUE THREAD

**Issue by goloroden** [Yelp/dumb-init#73]
### Steps to reproduce

```
$ docker run -it mhart/alpine-node:6 sh
# wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.0.1/dumb-init_1.0.1_amd64
```

### Expected result

`dumb-init` is installed, as it happens when using the `ubuntu` container, e.g..

### Actual result

An error message is returned by wget:

> Connecting to github.com (192.30.252.120:443)
> wget: can't execute 'ssl_helper': No such file or directory
> wget: error getting response: Connection reset by peer

Any thoughts on this?

**Comment by goloroden** [comment]
Okay, forget it … it was a problem with the CA certificates on Alpine Linux. You need to run

```
# apk update
# apk add ca-certificates
# update-ca-certificates
```

before running `wget`, then it works :-)

**Comment by mikecroft** [comment]
FYI for others coming across this, adding the above commands to my Dockerfile did not work, I needed to specifically add the `ca-certificates` to `wget` like this:

```
 RUN   apk update \                                                                                                                                                                                                                        
  &&   apk add ca-certificates wget \                                                                                                                                                                                                      
  &&   update-ca-certificates    
```

**Comment by tvalasek** [comment]
openssl package may be required too:

apk update && apk add ca-certificates && update-ca-certificates && apk add openssl

**Comment by asottile** [comment]
How difficult would it be to make an apk package for dumb-init?  We're experienced in debian packaging but unfamiliar with alpine's ecosystem and would love help if it's possible

**Comment by igorsantos07** [comment]
For those who arrive here, another solution is simply to use `curl` instead, if your idea is to run install scripts. It sounds even simpler, with less options to deal with - the default is to send to stdin for instance.

Example: to install `composer` on `php:7-fpm-alpine` I did the following:
`RUN curl https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer | php -- --quiet`

instead of what's [suggested by Composer](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) (that stumbles upon the CA issues on this post):
`RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer -O - -q | php -- --quiet
`

**Comment by vinyll** [comment]
I had

    wget: can't execute 'ssl_helper': No such file or directory
    wget: error getting response: Connection reset by peer

`apk add openssl` sloved in my case

**Comment by samrocketman** [comment]
I frown upon `curl | bash` installation instructions (`curl | php` is no different).  I hope dumb-init never adopts such insecure recommendations as instructions.  It grooms users with poor behaviors.

**Comment by dhoer** [comment]
As of Alpine Linux 3.3 there exists a new --no-cache option for apk. It allows users to install packages with an index that is updated and used on-the-fly and not cached locally:

`RUN apk --no-cache add openssl`
