### ISSUE TITLE
Official dumb-init image on Docker Hub?

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/dumb-init#74]
I see a few [dumb-init images](https://hub.docker.com/search/?q=dumb-init) on the docker hub, but none look "official".

Might be worth publishing an Ubuntu-based image with dumb-init added, maybe some other base OSes.

**Comment by asottile** [comment]
Do we have a @yelp account we can use?

**Comment by dnephin** [comment]
https://hub.docker.com/r/yelp/

**Comment by chriskuehl** [comment]
This seems like a good idea.

We'd probably want to support a few modified base images: `ubuntu:trusty`, `ubuntu:xenial`, `debian:wheezy`, `debian:jessie`, etc. So the question is how we want to publish these.

Some possibilities:

* **All distros under the same image name, with different tags for each version.** `yelp/dumb-init:trusty`, `yelp/dumb-init:jessie`. This is the shortest and simplest, but it's a little weird that it contains many different distros under one image name. The `latest` tag would probably point to the latest stable Ubuntu image.
* **Separate image names for each distro.** `yelp/dumb-init-ubuntu:trusty`, `yelp-dumb-init-debian:jessie`, etc. `latest` would just be the latest stable version of each distro.
* Something else?

Any thoughts on which of these is preferable?

**Comment by ailispaw** [comment]
`dumb-init` was built statically.
If a docker host has `dumb-init`, I use it just as below with any linux images.

```
docker run -d -v /path/to/dumb-init:/dumb-init:ro --entrypoint=/dumb-init <image> <command>
```

**Comment by stevenschlansker** [comment]
Personally, I think the value add of a `dumb-init` image is low.  `dumb-init` is not itself a service, you build a service on top of it.  So the only possible use case would be as a base for other images.  And now the end user service is relying on `dumb-init`'s choice of base, keeping updated with security patches, etc.  Do you really want to be responsible for rebuilding all of these images every time there's a critical security patch?  (OpenSSL breaking horribly every 2 months?)

It also completely breaks composition.  Since Docker images are single parent, I can have *exactly one* Docker-distributed package involved in any container.  If `dumb-init` and `magic-service` both produce Docker images and I want to run `magic-service` under `dumb-init`, there is no easy way to combine them.  You end up making your own build anyway.

(Obviously I'm being a party pooper and won't press further, I just won't use it -- I just think the community jumping on "everything must be a Docker image!!!!" is really shortsighted and does not help build good software.)

**Comment by ibm-om** [comment]
@stevenschlansker, your comments and skepticism are right on... however, the inability for Docker to clean up after itself or allow containers to exit before sending SIGKILL is a major impediment to progress too. There may be rationales for why Docker chose to not 'deal' with the container functions, but that doesn't change how frustrating it is to have to manually release loop-devices and kill zombies all the time.

**Comment by stevenschlansker** [comment]
Oh, I agree, the reason I am watching this project at all is indirectly because of how pissed I am that Docker has not fixed these long standing issues that hit every single user at some point.  So I am 100% in agreement that `dumb-init` fills a needed void, I just don't think Docker packaging actually solves any problems 😄

**Comment by EvanKrall** [comment]
@chriskuehl seems like the second option is better - I agree that having different distros under the same tag is weird.

@stevenschlansker I agree not everything needs to be distributed as a docker image, but in this case dumb-init is primarily meant to be used in Docker. I think most people are going to end up writing a Dockerfile like

```
FROM ubuntu:xenial
RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64
RUN chmod +x /usr/local/bin/dumb-init
```

Might as well optimize that.

I do also see there are complexities with keeping the image up to date. Can the docker hub's Trusted Builds feature help with this? (It doesn't appear to trigger a rebuild when the image behind your FROM line changes, but maybe we could trigger it manually?)

**Comment by chriskuehl** [comment]
@stevenschlansker definitely agree with your concerns as well. I'm unlikely to use a dumb-init image as the base for any of my production containers, but would definitely find it useful interactively (I pretty frequently start ubuntu/debian containers for one-off testing or building, would be great to have a base image with a dumb-init entrypoint for that).

**Comment by bukzor** [comment]
I'm -1 on trying to maintain this. It can't cover everyone's use case, but more importantly it will bitrot the moment we turn away.

I believe the solution is documentation. "Here's the two lines to put in your docker file: ..."

That said, a dumb-init image based on the scratch image doesn't have any of the above problems, but I don't know if anyone would use it.

**Comment by samrocketman** [comment]
+1 to documentation rather than a docker image.  I think it makes more sense to document how one would create the "from scratch" image around Yelp dumb-init.

**Comment by chriskuehl** [comment]
@bukzor I'd use an "official" dumb-init image if we had one, but only for interactive poking around.

Would anybody else use an image if we had one? If not, I'm happy with closing this ticket -- I can always make my own image :)

**Comment by chriskuehl** [comment]
It sounds like not many people are interested in "official" dumb-init images, so I'm going to close this issue for now.

With that said, I just created a bunch of images myself:
https://github.com/chriskuehl/dumb-init-dockers
https://hub.docker.com/r/ckuehl/dumb-init/tags/

These are intended for interactive usage; I've added a few Debian and Ubuntu flavors. You can use them like `docker run ckuehl/dumb-init whoami` (defaults to Debian jessie) or a specific tag, e.g. `docker run ckuehl/dumb-init:ubuntu-xenial whoami`.

**Comment by chriskuehl** [comment]
Side note: it actually turns out you can make DockerHub re-trigger builds automatically when another image (e.g. your base image) changes:

![](https://i.fluffy.cc/wwwjmrSpJqJ9kNr7x66m0QqkwHlr2bXM.png)
